language: python
matrix:
  include:
  - python: "3.7"
    env: TOXENV=py37
  - python: "3.7"
    env: TOXENV=codestyle
    before_install: true

install:
  - pip install tox
#  - pip install -r requirements.txt

script: tox
